language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("RecursiveFiltering"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("RecursiveFiltering")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
